### ISSUE TITLE
tcpip/seqnum/LessThan has a math calculation bug.

### ISSUE THREAD

**Issue by fanpei91** [google/netstack#14]
[seqnum.LessThan](https://github.com/google/netstack/blob/f833c4a17325122f85899ac7abae6ec738af2238/tcpip/seqnum/seqnum.go#L26) :
```go
func (v Value) LessThan(w Value) bool {
	return int32(v-w) < 0
}
```

It will be false at this case:

```go
func main() {
       var tsRecent uint32
       var tsVal  uint32 = 3744464773
       fmt.Println(int32(tsRecent-tsVal) < 0)  //  false
}
```

This version works correctly.

```go
func (v Value) LessThan(w Value) bool {
	return int64(v)- int64(w) < 0
}
```

**Comment by hbhasker** [comment]
I believe this is correct. The reason is sequence numbers wrap around and TCP window size is capped at 1/2 the sequence space (i.e 2^32/2). Which means that 0 is in fact > 3744465773 and not less as otherwise the permitted window will be > 2 ^32/2 and that would break down the strict ordering logic of sequence numbers.

**Comment by fanpei91** [comment]
I see, thank you for your explanation. I understand now why the window scale factor is 14.

**Comment by fanpei91** [comment]
One question: Why there is no implementation of [PAWS](https://tools.ietf.org/html/rfc1323#page-17)?

**Comment by hbhasker** [comment]
PAWS has been on my todo list forever. It required first implementing
support for Timestamps which was done but then we had other things like
SACK that took priority. PAWS is something we intend to implement in the
future. Current uses of netstack ran little risk of wrap around as it's not
used in situations where the sequence number could wrap around that fast
for PAWS to be required.

-bhasker

**Comment by fanpei91** [comment]
I am forwarding SACK and PAWS.

**Comment by tamird** [comment]
Can this issue be closed?
